version: "3.8"

services:
    mqtt_app:
        build: ./mqtt_app
        env_file:
            - .env
        depends_on:
            - mosquitto
            - mongo

    rest_app:
        build: ./rest_app
        env_file:
            - .env
        ports:
            - "5000:5000"
        depends_on:
            - mongo

    # bot_app:
    #     build: ./bot_app
    #     env_file:
    #         - .env
    #     ports:
    #         - "8000:8000"
    #     depends_on:
    #         - mongo
    #     restart: always

    mosquitto:
        image: eclipse-mosquitto
        ports:
            - "1883:1883"
        volumes:
            - ./mosquitto/config:/mosquitto/config
            - ./mosquitto/data:/mosquitto/data
            - ./mosquitto/log:/mosquitto/log

    mongo:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - ./mongo/data:/data/db
            - ./mongo/init:/docker-entrypoint-initdb.d
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
          MONGO_INITDB_DATABASE: rtn_db 
          
    mongo-express:
        image: mongo-express
        ports:
        - "8081:8081"
        # networks:
        # - my-networks
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
            ME_CONFIG_BASICAUTH: false
            TZ: "Asia/Bangkok"
        depends_on:
            - mongo

    # m5stickc_pir:
    #     build: ./m5stickc_pir
    #     env_file:
    #         - .env
    #     depends_on:
    #         - mosquitto
    #         - rest_app
    #     restart: always
